### ISSUE TITLE
Fix HTTP parsing on MacOs

### ISSUE THREAD

**Issue by hellxcz** [vlingo-net/vlingo-net-http#5] opened 2020-12-26 21:14 UTC
I tried to create a simple HTTP service with simple GET method handle.
On MacOS there is a different NewLine convention ("\r\n"). Handling of such situation is present in code in RequestParser code, unfortunately dotNet String.IndexOf("\n", ..) does not work properly. Always returns -1 as index on MacOS.
Simple change from "\n":string to '\n':char fixes the issue.

**Comment by tjaskula** [comment] 2020-12-26 21:30
Thanks for reporting the issue. 

However I don't get quite well what is the issue. Is there an exception, handler not responding to the request or something else? Can you reproduce the problem with an UT?

**Comment by hellxcz** [comment] 2020-12-27 11:50
Hi.
it fails on bad parsing of HTTP request.
On MacOS the new line is "\r\n". And when you would try to find the "\n" in such string, dotNet will return -1 as not found. 
Consequence of this is, that parsing of HTTP does not work at all.

**Comment by tjaskula** [comment] 2020-12-27 11:56
I have Mac and everything developed here was on Mac. I didn’t see any problem before. It has to be culture specific then. Without your change is there any test failing? Could you reproduce the failure with a UT so I can look at it?

**Comment by hellxcz** [comment] 2020-12-27 20:28
I found this, when it was running with small sample and I was calling it over postman.
It is reproducible, when in ResourceTestFixtures i changed the NewLineDelimiter to "\r\n". Than all tests, which are dependent on RequestParser started to fail.

**Comment by VaughnVernon** [comment] 2020-12-27 20:37
https://tools.ietf.org/html/rfc2616#section-2.2

https://stackoverflow.com/questions/5757290/http-header-line-break-style

**Comment by hellxcz** [comment] 2020-12-27 21:01
Hi Vaugn.
I dont want to be evil. Naming is not maybe correct, but it referred to ResourceTestFixtures, where fixture messages for test runs are defined. When those messages are changed to contain "\r\n", it should reproduce issue. On my machine it did.

**Comment by tjaskula** [comment] 2020-12-27 21:06
> Hi Vaugn.
> I dont want to be evil. Naming is not maybe correct, but it referred to ResourceTestFixtures, where fixture messages for test runs are defined. When those messages are changed to contain "\r\n", it should reproduce issue. On my machine it did.

I just don't get how your PR https://github.com/vlingo-net/vlingo-net-http/pull/6/ fix the issue. The thing you've done is replacing inlined `\n` with the same thing from a variable.

You mean that actually the code is not handling properly `\r\n` but the PR is not fixing that point ?

**Comment by hellxcz** [comment] 2020-12-27 21:14
That NewLineDelimiter in RequestParser (not in ResourceTestFixtures, where it is string for convenient way to replace delimiter in test messages) is of type char with value of '\n'. Looks the same, but when it is string, as original code, the String.IndexOf method will not find "\n" properly, when delimiter is of value "\r\n". Actually it will not find it at all. Thats odd thing in dotNet core. Changing it to char '\n' will fix this behaviour and starts to work.

**Comment by tjaskula** [comment] 2020-12-27 21:21
Ok, I understand. I'll give it a try.

**Comment by VaughnVernon** [comment] 2020-12-27 21:23
If the line ends with CRLF, that's two characters. I don't understand how attempting to find the single character LF can't succeed. The single characters CR and LF are in the string. You should be able to find any of CR or LF or CRLF.

What am I missing?

**Comment by hellxcz** [comment] 2020-12-27 21:23
I was also confused and spent some time with debugging, because it does not make too much sense. But it fixed broken behaviour with real running app. Simple one, but debugged with real calls from postman.

**Comment by hellxcz** [comment] 2020-12-27 21:35
well, I found it. Its a strange stuff in .net 5.
check out this fiddle -  https://dotnetfiddle.net/mMyDyz

when it's changed to .net 4.xxx both works fine.

**Comment by tjaskula** [comment] 2020-12-27 21:43
Wow. Looks like you found a bug on .NET side 👍🏻

**Comment by hellxcz** [comment] 2020-12-27 21:46
Man, that was not a purpose :D

**Comment by VaughnVernon** [comment] 2020-12-27 21:48
Are you using Framework or Core? We use Core, and I think Core 3 (or 2). @tjaskula ?

**Comment by tjaskula** [comment] 2020-12-27 21:49
@VaughnVernon it's .NET 5 now. Core is replaced slowly by it

**Comment by hellxcz** [comment] 2020-12-27 21:49
Thats was .net 5. there will be no Core version.

**Comment by VaughnVernon** [comment] 2020-12-27 21:53
LOL, there's no way for me to keep up with Microsoft's every move.

1. .NET Framework
2. .NET Standard & .NET Core
3. .NET Core
4. .NET
5. .???

**Comment by tjaskula** [comment] 2020-12-27 21:54
.NET 5 is new implementation of .NET Core and Framework. Cross platform which wipes out all previous.

**Comment by VaughnVernon** [comment] 2020-12-27 21:55
Makes sense. I'll try to remember.

**Comment by tjaskula** [comment] 2020-12-27 21:56
However this '\n' parsing string is a glitch for me. An issue should be opened there :)

**Comment by hellxcz** [comment] 2020-12-27 22:05
Guys, I'm sorry for bothering. This really seems like weird stuff on .NET 5 side. Who would expect such thing ?
Question is, if Microsoft dotNet team will fix this, or if they will present this as new feature, that needs to be manually migrated.
Thanks for nice discussion.

**Comment by VaughnVernon** [comment] 2020-12-27 22:06
Given that a missing LF or CRLF is an HTTP error, should you try up to two times as follows?

if (Find(CRLF)) use line
else if (Find(LF)) use line
else error

**Comment by tjaskula** [comment] 2020-12-27 22:07
@hellxcz No bothering at all. I'm glad you reported the issue. At least we know there is a problem.

**Comment by tjaskula** [comment] 2020-12-28 20:07
Addressed in https://github.com/vlingo-net/vlingo-net-http/compare/380816e16a69...7b2d9c6d7fe6

**Closed by tjaskula** 2020-12-28 20:07 UTC
